### ISSUE TITLE
Overriding the mush-rgb-state-* doesn't work

### ISSUE THREAD

**Issue by melyux** [piitaya/lovelace-mushroom-themes#10]
Great stuff! I tried overriding in my own theme the default color of lights, using ```mush-rgb-state-light: var(--rgb-amber)```, but this had no effect. The other kinds of overrides do work though, so I can't tell why these ones don't.

**Comment by gadgetchnnel** [comment]
I had similar when trying to override mush-rgb-state-entity, I think the issue is that the variable `--rgb-amber` is local to the card and not available to the theme.

Changing it to use the actual rgb values, like `mush-rgb-state-light: 255, 193, 7`, works.

**Comment by piitaya** [comment]
Yep I think it's the issue. You can define --mush-rgb-amber and use it in your theme 🙂

**Comment by platini76** [comment]
hello, I am trying to change color of the icon on my lock to invert red and green

`type: custom:mushroom-lock-card
entity: lock.serratura_ingresso
fill_container: false
icon: ''
mush-rgb-state-lock-locked: --rgb-red	`

did not work... any suggestions?

**Comment by platini76** [comment]
any news about it?

**Comment by piitaya** [comment]
`mush-rgb-state-lock-locked` should be used in a theme, not on the card config.

I'm closing the issue as it's not really an issue but a question.

**Comment by platini76** [comment]
sorry for question, but can you please explain briefly what I have to do to have this override on my lock card?
