### ISSUE TITLE
stretch  icon

### ISSUE THREAD

**Issue by andrey80nik** [piitaya/lovelace-mushroom-themes#2]
Is it possible to stretch icons by width?
to fill the line from edge to edge, for beauty.
![image](https://user-images.githubusercontent.com/67071776/153425248-96a1ff42-5500-4322-9058-911ebdda5029.png)
to get it like this
![image](https://user-images.githubusercontent.com/67071776/153427316-020e0acd-4b5a-4c42-86ce-a66c45e6a3f4.png)

**Comment by pierrecle** [comment]
Hi, this will be a card option, not theme. Issue is here: https://github.com/piitaya/lovelace-mushroom/issues/111
