### ISSUE TITLE
Color Icon when state is off on Mushroom entity card

### ISSUE THREAD

**Issue by stianmt** [piitaya/lovelace-mushroom-themes#20]
Hi

I tried to add a color template to change the color on the entity card. But seems like it is not possible to add color to an icon when state is off.

I have a few magnet sensors on my windows, and it would be great if I could set the color of the icon to green when they are closed (State is off but set to closed since entity has device class "opening" which sets state off to closed (https://www.home-assistant.io/integrations/binary_sensor/))

Is it possible to add the opportunity for color template like it is for the icon template?

**Comment by juliandsp91** [comment]
In case somebody needs, here is an example of a icon color template:

This sets the color based on entity state:

```
icon_color: |
  {% if is_state('switch.lavadora_power_off', 'off') %}
    grey
  {% else %}
    blue
  {% endif %}
```

This sets the color based on entity attribute "current":

```
icon_color: |
  {% if state_attr('script.activa_secuencia_dormir', 'current') == 1%}
    blue
  {% else %}
    grey
  {% endif %}
```

Only need to change the entities name, states and colors.
