### ISSUE TITLE
Formatting for each card type

### ISSUE THREAD

**Issue by cataseven** [piitaya/lovelace-mushroom-themes#25]
Is it possible to adjust card height and width for each card type? When I change card size on yaml file all cards changes. I want small person card but big light card or medium size climate card.

Do you have any plans for that?

Btw, this is a great work! Big thanks!

**Comment by piitaya** [comment]
What do you mean by size ? 
It's not possible de change the height and width per domain but you can use grid card or stack card to organize your dashboard 🙂
