### ISSUE TITLE
Ability to change font size of Chip text 

### ISSUE THREAD

**Issue by malcolmturnbull** [piitaya/lovelace-mushroom-themes#3]
I am probably just missing something in Inspector and the stylesheet, but is there currently a term e.g., how there is mush-chip-height, or mush-title-font-size? 

I am trying to increase their size so they are easier to use on a touch display. I love these lovelace addons - thank you for all the great work!

**Comment by piitaya** [comment]
This will be fixed in the next mushroom release : https://github.com/piitaya/lovelace-mushroom/pull/121
The font-size for span, icon and svg will be adjusted automatically.

**Comment by Kev1000000** [comment]
Maybe I am missing something, but how do I adjust the font size manually of the chip text?

**Comment by piitaya** [comment]
@Kev1000000 The font-size (and icon size) is automatically adjusted with the chip height. The default chip height is `36px`. If you set it to `72px`, the font-size will be doubled too.

**Comment by berkansezer77** [comment]
> @Kev1000000 The font-size (and icon size) is automatically adjusted with the chip height. The default chip height is `36px`. If you set it to `72px`, the font-size will be doubled too.

How can we set this to 72px?

**Comment by piitaya** [comment]
You can do this using theme : https://github.com/piitaya/lovelace-mushroom-themes

**Comment by jpoeppelman1** [comment]
> You can do this using theme : https://github.com/piitaya/lovelace-mushroom-themes

I'm having the same issue.  How can I override the primary or secondary text font size for a specific card only?  I don't want to change this at the global theme level.  Any help?

**Comment by lyczko** [comment]
> How can I override the primary or secondary text font size for a specific card only? I don't want to change this at the global theme level. Any help?

any idea?

**Comment by horga83** [comment]
It says the theme is not required any more as of 2022.11.  If that is the case how would one change the font for an individual card such as a mushroom entity card?  I've been playing with this for a few hours and it has me stumped.  I can change the background colour like so:
      - type: custom:mushroom-entity-card
        entity: sensor.upstairs_atc_temperature
        fill_container: true
        card_mod:
          style: |
            :host {
              --ha-card-background: teal;
            }
but have not been successful changing the font size.  Help greatly appreciated.

**Comment by horga83** [comment]
Ah checkout the mushroom theme, there is a list of settings in there, for example under "card" there is:

 mush-card-primary-font-size: 14px;

That will set the text in a card. Here is an example:
```
      - type: custom:mushroom-entity-card
        entity: sensor.downstairs_atc_temperature
        card_mod:
          style: |
            :host {
              --ha-card-background: green;
              --mush-card-primary-font-size: 26px;
            }
```

**Comment by piitaya** [comment]
I close it as theme variables can be set for one card using card-mod.
