### ISSUE TITLE
Downloading Mushroom Themes in HACS gives "requires 2022.11" error

### ISSUE THREAD

**Issue by LEGOW-HOME** [piitaya/lovelace-mushroom-themes#32]
Attempting to install/download however it issues an error stating that it requires 2022.11? 
Selecting "download" goes into endless wait.

<img width="614" alt="Screen Shot 2022-10-26 at 3 24 04 PM" src="https://user-images.githubusercontent.com/116699524/198150277-50cd5552-fe2f-46f1-af39-01cab6336669.png">

**Comment by TheFes** [comment]
Well, seems that the message is clear, you need 2022.11 for the latest version (for which the beta just started).
