### ISSUE TITLE
0.0.6 requires pre release version of home assistant

### ISSUE THREAD

**Issue by siparker** [piitaya/lovelace-mushroom-themes#36]
If i try to install mushroom themes and choose the latest version it requires minimum version of home assistant 2022.11.0b0 which is a pre release version. 
This seems like it might have been an error?

**Comment by ManuFlosoYT** [comment]
![image](https://user-images.githubusercontent.com/46373952/198853626-68af000e-bc47-41dc-b533-e4a0e117156d.png)

I have the same problem

**Comment by piitaya** [comment]
Hello ! The message is clear, you need the 2022.11 version to upgrade.
