### ISSUE TITLE
can't install because is asking for 2022.11.0b0 to be installed

### ISSUE THREAD

**Issue by antoniopacheco** [piitaya/lovelace-mushroom-themes#37]
I get the error:

You are running Home Assistant version '2022.10.5', but this repository requires minimum version '2022.11.0b0' to be installed.
I think it might happened in the last release in this line:
https://github.com/piitaya/lovelace-mushroom-themes/blob/main/hacs.json#L3

**Comment by piitaya** [comment]
Yes, the new version is only for the 2022.11 version
