### ISSUE TITLE
Sudden appearance of chip border after update 2.2.0

### ISSUE THREAD

**Issue by stefsoma** [piitaya/lovelace-mushroom-themes#38]
After updating to Mushroom v2.2.0 chips shows with a border. Used to be without. How can this be solved? Tried to play around with styles but no change.

![image](https://user-images.githubusercontent.com/1675741/199000992-03f0c8e2-223e-4659-837b-ab0d27c8c848.png)

>     This used to work
card_mod:
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
          --chip-spacing: 0;
        }

**Comment by piitaya** [comment]
How does it work with the latest version? I should be fixed

**Comment by stefsoma** [comment]
> How does it work with the latest version? It should be fixed

It is fixed now. Shadow was obviously removed and replaced with border. Custom CSS works again so I were able to customize it to my preferance. Thanks for your great work!
