### ISSUE TITLE
Ability to keep changes after update

### ISSUE THREAD

**Issue by Glennesink** [piitaya/lovelace-mushroom-themes#40]
Loving the mushroom Themes 

I use 2 backgrounds for light and dark mode, when updating the config for these are wiped.
Would it be possible to make a custom section where these are changed, and will be called even when updated.

Keep up the great work!

**Comment by piitaya** [comment]
We can do that because it's how Hacs works with themes. I suggest you to copy/paste the theme you like into a new file and folder with another name and do your overrides inside this file.

**Comment by Glennesink** [comment]
Got it nice thanks!
