### ISSUE TITLE
New Theme (Mix of themes) Square theme with round Icons

### ISSUE THREAD

**Issue by j-loewen** [piitaya/lovelace-mushroom-themes#42]
Hello,

could you please make a theme where is everything square like in the theme "Mushroom Square" or "Mushroom Square Shadow" with the exception of the Icon. The Icon should be a circle like in the Theme "Mushroom" or "Mushroom Shadow"

With best regards

Johann

**Comment by piitaya** [comment]
You can define your own theme if you want. I can not propose one theme for each variation 😅
