### ISSUE TITLE
HA 10.11 Borders

### ISSUE THREAD

**Issue by SucubusJenny** [piitaya/lovelace-mushroom-themes#43]
Since Home assistant 10.11 the default borders have appeared on the mushroom themes and they look far worse than the old look pre 10.11
![Themes](https://user-images.githubusercontent.com/60557616/202062916-96327fbe-1200-4aba-9e44-e0ffdb305408.png)

**Comment by piitaya** [comment]
I close it as there is already some closed issues about it.
