### ISSUE TITLE
Chip Outline

### ISSUE THREAD

**Issue by aarnaegg** [piitaya/lovelace-mushroom-themes#44]
I used to have no outline for the chip cards. After the recent updates, I can not get rid of them. I don't know what I am missing? I have tried removing every border option I can see.
![Screenshot 2022-11-18 170049](https://user-images.githubusercontent.com/99874918/202822519-7074a066-0f11-4bb7-9055-3d8e57cba431.png)
Does anyone know how to remove the chip card outline?

**Comment by aarnaegg** [comment]
Attached is my current config in config.yaml
![Screenshot 2022-11-18 170326](https://user-images.githubusercontent.com/99874918/202822626-7ba8758f-2c8e-4c07-abdb-81dc432b3d0d.png)

**Comment by backslashV** [comment]
It's not just the chip. All cards now have outlines. It'd be great if we could change it back to no outline.

**Comment by piitaya** [comment]
I close it as it's now the default HA theme and there is mushroom shadow theme to remove it.
