### ISSUE TITLE
Badges & Square Mushroom Template

### ISSUE THREAD

**Issue by j6s33m** [piitaya/lovelace-mushroom-themes#57]
Love the new custom Mushroom Template badge options, but noticed that my preferred theme, "Mushroom Square Shadow", does not square up the badges. Is there an update in the future where this theme will fix that?

**Comment by piitaya** [comment]
It's fixed with the [0.0.10](https://github.com/piitaya/lovelace-mushroom-themes/releases/tag/v0.0.10) version.
Built-in badges from Home Assistant will also be supported with 2024.9 release.

**Comment by j6s33m** [comment]
Thank you
