### ISSUE TITLE
Problem with Lovelace category during HACS install

### ISSUE THREAD

**Issue by patrickse** [piitaya/lovelace-mushroom-themes#6]
Just installed the theme using hacs. The README.md states that I should choose **Lovelace** as the category for the custom repo. The installation failed because of a not compatible folder layout. Instead of **Lovelace** select **Theme** and everything will work fine.

**Comment by antonio1475** [comment]
> Just installed the theme using hacs. The README.md states that I should choose **Lovelace** as the category for the custom repo. The installation failed because of a not compatible folder layout. Instead of **Lovelace** select **Theme** and everything will work fine.

Same here, but if I install it as Theme I cannot set it on a Dashboard page, even after Restarting. A I missing a step? Are you able to choose the 
![20312CA8-6417-45C3-85D7-FC2F3ABDFEE6](https://user-images.githubusercontent.com/63130724/154153351-3948714b-4a86-4cde-aba0-0fbda48c194a.png)
theme?

**Comment by nagug** [comment]
did you include the config file with the following code

`frontend:
  ... # your configuration.
  themes: !include_dir_merge_named themes
  ... # your configuration.`

**Comment by antonio1475** [comment]
> did you include the config file with the following code
> 
> `frontend: themes: !include_dir_merge_named themes`

Thank you. I hadn't - I thought by installing via HACS, that part wasn't necessary. Solved. Thx
