### ISSUE TITLE
Fan and Light Card Colors not working

### ISSUE THREAD

**Issue by jaredguiles** [piitaya/lovelace-mushroom-themes#9]
When trying to use the _mush-rgb-state-light_ & _mush-rgb-state-fan_ variable, the changes are not applied. Only changing colors and other options like font size and padding are working. 

For example, I would like to change the color of the fans to be light blue from green, and lights to be amber. 

This does not work:
```
mush-rgb-state-light: var(--rgb-amber)
mush-rgb-state-fan: var(--rgb-light-blue)
```
This works, but also changes anything else that is green. 
```
mush-rgb-green: 3, 169, 244
```

**Comment by piitaya** [comment]
Did you try
```yaml
mush-rgb-state-fan: 3, 169, 244
```
or 
```yaml
mush-rgb-state-fan: var(--mush-rgb-green)
```
?

**Comment by piitaya** [comment]
Try my proposals

**Comment by piitaya** [comment]
Cool! The documentation is not perfect, I will update it ! 🙂
